### ISSUE TITLE
code not usable

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [drupol/phpblockchain#1]
it seems the library path in the code is wrong.
after git clone the repo, there is no "drupol" folder containing the classes.

**Comment by drupol** [comment]
Erm... Have you run composer install ?

**Comment by ROBERT-MCDOWELL** [comment]
well, run compose to install php project is not a mandatory way to use php, espcially for an old school guy like me who is developing php since 1999.

**Comment by ROBERT-MCDOWELL** [comment]
as compile myself and manage several version of php, and as I don't use composer for my production work I have to install it from scratch.

**Comment by drupol** [comment]
This project requires the use of modern PHP practices, this is why it requires `composer install`.

I'm afraid but I won't be able to help if you're not keen to use it.

**Comment by ROBERT-MCDOWELL** [comment]
modern is not the right term anyhow (plenty of php-7 php-8 projects don't user composer)
I give up installing composer as it shows
Fatal error: Uncaught PharException: phar "/usr/local/php7/bin/composer.phar" has a broken signature in /usr/local/php7/bin/composer.phar:23
no time to play with this s...t

**Comment by drupol** [comment]
Faire enough, good luck :-)
